### ISSUE TITLE
Разработать компонент синхронизации данных

### ISSUE THREAD

**Issue by hamzreg** [amunra2/team-dev-bmstu-iu7#18]
### Цель
Постоянное обращение к lks.bmstu.ru ресурсозатратно. Для оптимизации получения сведений о парах создается база данных (#4), которую нужно обновлять в соответствии с актуальным расписанием. Для этого необходим компонент синхронизации данных.

### Ожидаемый результат

Компонент синхронизации данных представляет из себя модуль, который:
* отправляет запрос lks.bmstu.ru;
* получает ответ в формате json;
* преобразует полученные данные в форму представления их в базе данных;
* обновляет данные в базе.

### Задачи

- [x]  реализовать удаление данных из базы по запросам (#17)
- [x]  реализовать получение данных из lks.bmstu.ru в формате json:
  - [x]  получить uuid групп
  - [x]  получить расписание каждой группы
- [x] данные пар каждой группы преобразовать в формат базы данных (#4)
- [x] добавить данные в базу данных по запросам (#17)
